### ISSUE TITLE
Не включается модуль в админ панели

### ISSUE THREAD

**Issue by Messer64** [Tseka85/opencart3-exchange1c#1]
Модули/Расширения - Модули - Обмен данными с 1C v8.x (Tesla-Chita) (Статус Отключен) в настройках модуля, модуль включен.
Соединиться с сайтом не получается, выдает ошибку Соединение не установлено.
OpenCart - Version 3.0.3.2

Возможно ли из за этого не подключение 1с с моим сайтом7
![1](https://user-images.githubusercontent.com/67359057/85506377-4bbb2580-b601-11ea-9a65-4b7708013d37.PNG)
![2](https://user-images.githubusercontent.com/67359057/85506379-4d84e900-b601-11ea-8341-60dd00b68b6c.PNG)
@Tseka85

**Comment by Tseka85** [comment]
> Модули/Расширения - Модули - Обмен данными с 1C v8.x (Tesla-Chita) (Статус Отключен) в настройках модуля, модуль включен.

  Он на самом деле включён , просто в списках модулях отображается как выключен , это какой-то баг третьей версии опенкарта . Не было времени это исправлять . Модуль и без этого рабочий .

**Comment by Messer64** [comment]
Подскажите какая та инструкция подключения есть?Или подскажите в какую сторону копать, не могу установить подключение с сайтом, куда мне рыть чтобы установить связь с сайтом -- Колычев Артем-- ООО "ПромТехПласт"--www.ptp64.ru+79271202977Саратовская область, г. Балаково   24.06.2020, 11:53, "Dmitro" <notifications@github.com>: Модули/Расширения - Модули - Обмен данными с 1C v8.x (Tesla-Chita) (Статус Отключен) в настройках модуля, модуль включен.Он на самом деле включён , просто в списках модулях отображается как выключен , это какой-то баг третьей версии опенкарта . Не было времени это исправлять . Модуль и без этого рабочий .—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tseka85** [comment]
> Соединиться с сайтом не получается, выдает ошибку Соединение не установлено.

 У вас модуль правильно установлен ?   Файл по пути export/exchange1c.php есть ?

**Comment by Tseka85** [comment]
https://ibb.co/YQrscjy

**Comment by Tseka85** [comment]
<a href="https://ibb.co/MPXMHj6"><img src="https://i.ibb.co/1RS8Np6/image.jpg" alt="image" border="0"></a>

**Comment by Messer64** [comment]
Да путь указан полностью, все папки были перенесены, модуль отображается в настройках его включил, пароль от админки указал-- Колычев Артем-- ООО "ПромТехПласт"--www.ptp64.ru+79271202977Саратовская область, г. Балаково   24.06.2020, 12:10, "Dmitro" <notifications@github.com>: —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Messer64** [comment]
Но подключение все равно отсутствует.Ошибка в 1С:Не удалось установить соединение с сервером. Авторизация пользователя не выполнена.___Путь в 1С - https://ptp64.shop/export/exchange1c.phpПуть скопировал из модуля и вставил    -- Колычев Артем-- ООО "ПромТехПласт"--www.ptp64.ru+79271202977Саратовская область, г. Балаково   24.06.2020, 12:10, "Dmitro" <notifications@github.com>: —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tseka85** [comment]
1) В 1С в настройках укажите http://ptp64.shop/export/exchange1c.php   и логин с паролем . ('http'  без  's'  ) 

2) В папку закиньте файл .htaccess  с  такими строками : 
  
RewriteCond %{HTTP:Authorization} ^Basic.*
RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization},L]

**Comment by Tseka85** [comment]
<a href="https://ibb.co/fHXHdQD"><img src="https://i.ibb.co/SB6BwJf/1.jpg" alt="1" border="0"></a>

**Comment by Tseka85** [comment]
[.htaccess.zip](https://github.com/Tseka85/opencart3-exchange1c/files/4831759/default.htaccess.zip)

**Comment by Messer64** [comment]
К сожалению, не подключается- -- Колычев Артем-- ООО "ПромТехПласт"--www.ptp64.ru+79271202977Саратовская область, г. Балаково   25.06.2020, 17:58, "Dmitro" <notifications@github.com>: .htaccess.zip—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Messer64** [comment]
В зависимости от протокола разные ошибки: при HTTPS ошибка: Не удалось установить соединение с сервером. Авторизация пользователя не выполнена.при HTTP ошибка: Не удалось установить соединение с сервером. Проверьте имя пользователя и пароль.Лог ошибок из админки показывает подключение с рабочего IP адреса: 2020-06-26 7:01:03 - Client IP address: 85.26.167.1002020-06-26 7:02:15 - Client IP address: 85.26.167.1002020-06-26 7:02:40 - Client IP address: 85.26.167.1002020-06-26 7:04:25 - Client IP address: 85.26.167.1002020-06-26 7:09:25 - Client IP address: 85.26.167.1002020-06-26 7:09:35 - Client IP address: 85.26.167.1002020-06-26 7:11:04 - Client IP address: 85.26.167.1002020-06-26 7:11:08 - Client IP address: 85.26.167.1002020-06-26 7:13:55 - Client IP address: 85.26.167.1002020-06-26 7:14:16 - Client IP address: 85.26.167.100   -- Колычев Артем-- ООО "ПромТехПласт"--www.ptp64.ru+79271202977Саратовская область, г. Балаково   25.06.2020, 17:58, "Dmitro" <notifications@github.com>: .htaccess.zip—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tseka85** [comment]
В общем вам надо с начало настроить модуль на стороне опенкарта , а потом уже с 1С пробовать . Вставляйте ваш путь http://ptp64.shop/export/exchange1c.php  в адресную строку браузера и смотрите , что получается . Когда всё работает , будет результат "success" как у меня ниже на скрине .
![success](https://user-images.githubusercontent.com/31914380/85831937-cb7af880-b797-11ea-8006-1beb1c717f3f.jpg)

**Comment by Messer64** [comment]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Session::__construct(), 0 passed in /var/www/u1022095/data/www/ptp64.shop/export/exchange1c.php on line 139 and at least 1 expected in /var/www/u1022095/data/www/ptp64.shop/system/library/session.php:24 Stack trace: #0 /var/www/u1022095/data/www/ptp64.shop/export/exchange1c.php(139): Session->__construct() #1 {main} thrown in /var/www/u1022095/data/www/ptp64.shop/system/library/session.php on line 24 Выдает фатальную ошибкуБуду разбираться тогда-- Колычев Артем-- ООО "ПромТехПласт"--www.ptp64.ru+79271202977Саратовская область, г. Балаково   26.06.2020, 11:29, "Dmitro" <notifications@github.com>: В общем вам надо с начало настроить модуль на стороне опенкарта , а потом уже с 1С пробовать . Вставляйте ваш путь http://ptp64.shop/export/exchange1c.php в адресную строку браузера и смотрите , что получается . Когда всё работает , будет результат "success" как у меня ниже на скрине .—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Messer64** [comment]
Не получается решить вопрос при открытии ссылки выбивается ошибка: Fatal error: Uncaught ArgumentCountError: Too few arguments to function Session::__construct(), 0 passed in /var/www/u1022095/data/www/ptp64.shop/export/exchange1c.php on line 139 and at least 1 expected in /var/www/u1022095/data/www/ptp64.shop/system/library/session.php:23 Stack trace: #0 /var/www/u1022095/data/www/ptp64.shop/export/exchange1c.php(139): Session->__construct() #1 {main} thrown in /var/www/u1022095/data/www/ptp64.shop/system/library/session.php on line 23День убил на поиск проблемы но так и не нашелСможете подсказать куда копать в поиске проблемы? -- Колычев Артем-- ООО "ПромТехПласт"--www.ptp64.ru+79271202977Саратовская область, г. Балаково   26.06.2020, 11:29, "Dmitro" <notifications@github.com>: В общем вам надо с начало настроить модуль на стороне опенкарта , а потом уже с 1С пробовать . Вставляйте ваш путь http://ptp64.shop/export/exchange1c.php в адресную строку браузера и смотрите , что получается . Когда всё работает , будет результат "success" как у меня ниже на скрине .—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Messer64** [comment]
Можно закрывать тему, вопрос решен полной переустановкой движка и настройкой с нуля на другом хостинге
