### ISSUE TITLE
Не выгружаются заказы в 1С

### ISSUE THREAD

**Issue by Maksimkeen** [Tseka85/opencart3-exchange1c#13]
Здравствуйте, подскажите, пожалуйста, в чём может быть проблема при выгрузке заказов в 1С УНФ 1.6.26.93

Интерактивный обмен
27.12.2020 3:16:47 Запуск загрузки заказов
Обработано: 0
Загружено: 0
Пропущено: 0
Обновлено: 0
Создано: 0
Обработано оплат: 0
Загружено оплат: 0
Пропущено оплат: 0
Обновлено оплат: 0
Создано оплат: 0
27.12.2020 3:16:48 Завершена загрузка заказов
Дополнительная информация:
Отправка файла на сервер: Получен пустой ответ сервера.
Не удалось прочитать данные, загруженные с сервера.

**Comment by Tseka85** [comment]
Мало информации от вас . Лог файл присылайте .

**Comment by Maksimkeen** [comment]
Здравствуйте.
[error_log_exchange1c.zip](https://github.com/Tseka85/opencart3-exchange1c/files/5797406/error_log_exchange1c.zip)

**Comment by Tseka85** [comment]
Добавить недостающие поля  в таблицу  "customer"  и  "order"  -  поля :  "middlename", "company_inn", "company_kpp"

Замените префикс oc_  на свой

```
ALTER TABLE `oc_customer` ADD `middlename` VARCHAR ( 32 ) NOT NULL AFTER `lastname` , ADD `company_inn` VARCHAR ( 32 ) NOT NULL AFTER `lastname` , ADD `company_kpp` VARCHAR ( 32 ) NOT NULL AFTER `lastname` , ADD company VARCHAR ( 32 ) NOT NULL AFTER lastname

ALTER TABLE `oc_order` ADD `middlename` VARCHAR ( 32 ) NOT NULL AFTER `lastname` , ADD `company_inn` VARCHAR ( 32 ) NOT NULL AFTER `lastname` , ADD `company_kpp` VARCHAR ( 32 ) NOT NULL AFTER `lastname` , ADD company VARCHAR ( 32 ) NOT NULL AFTER lastname

```

**Comment by Maksimkeen** [comment]
Спасибо большое!
