### ISSUE TITLE
Экспорт заказов, вопрос с валютой заказа

### ISSUE THREAD

**Issue by Anonames** [Tseka85/opencart3-exchange1c#16]
Добрый день, тестирую экспорт заказов, вопрос с валютой заказа магазин мультивалютный, а в экспорте заказов только рубли.
Опция
Заменять валюту при выгрузке: _руб._ - серого цвета
Как сделать пустое поле не пойму, мне нужно как написано в инструкции рядом: "если не указывать название валюты, тогда если покупатель оформит заказ в другой валюте, будет в заказе указана именно она"
Opencart ocStore 3.0.2.0

**Comment by Tseka85** [comment]
Добрый день, скиньте скрин . Не понятно какое поле не активно .

**Comment by Anonames** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/76214956/106476119-6155cf00-64af-11eb-9249-cfce9dbc56be.jpg)

**Comment by Anonames** [comment]
Поле активно но вписано руб. по умолчанию. Пустым его оставить не получается, а при таких настройках все цены в рублях.

**Comment by Tseka85** [comment]
По умолчанию оно пустое . Серая надпись .руб - это подсказка .

**Comment by Anonames** [comment]
Да, но при пустом поле экспорт заказов происходит в рублях, а не в валюте заказа, хотя рублей как валюты в магазине нет. Дополню позже скринами.

**Comment by Anonames** [comment]
![curency](https://user-images.githubusercontent.com/76214956/106568043-682a2380-653b-11eb-9a2e-88372cf6d689.jpg)
![order](https://user-images.githubusercontent.com/76214956/106568060-6fe9c800-653b-11eb-96be-0ea7c492c8a9.jpg)
![order_xml](https://user-images.githubusercontent.com/76214956/106568089-7710d600-653b-11eb-9e0e-956d96b41b94.jpg)
[log.txt](https://github.com/Tseka85/opencart3-exchange1c/files/5909483/log.txt)

**Comment by Tseka85** [comment]
Ок . Спасибо .  Ожидайте решение на днях . Я сюда напишу .

**Comment by Anonames** [comment]
выгрузка заказов

[orders.zip](https://github.com/Tseka85/opencart3-exchange1c/files/5925310/orders.zip)
