### ISSUE TITLE
SEO Производителей не формируется

### ISSUE THREAD

**Issue by AlektroNik** [Tseka85/opencart3-exchange1c#18]
SEO Поля Производителей остаются пустыми после генерации SEO:
[https://monosnap.com/file/pHKZNUwPImyCQOoZfNm2kSHMK67nzV](https://monosnap.com/file/pHKZNUwPImyCQOoZfNm2kSHMK67nzV)

**Конфигурация:**
1С УНФ 1.6
ocStore 3.0.2.0
Сборка модуля от 20.03.2021

**Comment by Tseka85** [comment]
Ок. Гляну на днях .

**Comment by Tseka85** [comment]
Смотрел , формируется . Скиньте свой import.xml

**Comment by AlektroNik** [comment]
import.xml не причем.
У меня почему-то даже Ручная генерация SEO по шаблонам не работала.
А сейчас запустил и заработало ... Чудеса блин :)
При выгрузке из 1С правда не проверял.
Спасибо.
