### ISSUE TITLE
Не сохраняются настройки модуля. 

### ISSUE THREAD

**Issue by pavelhar** [Tseka85/opencart3-exchange1c#2]
Не сохраняются настройки модуля 
![image](https://user-images.githubusercontent.com/34791744/95330528-57c9ab00-08b1-11eb-8a1e-6ab16b1a2e36.png)
Когда нажимаю применить, вроде сохраняются, после перезагрузки некоторые настройки сбрасываются, например такие как "не загружать цены" , всегда после релоада ДА, не создавать категории тоже ДА, всегда, подскажите, пожалуйста, куда копать, заранее спасибо)

**Comment by Tseka85** [comment]
Сейчас исправлю на гитхабе. Ожидайте .

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ср, 7 окт. 2020 г. в 15:28, pavelhar <notifications@github.com>:

**Comment by pavelhar** [comment]
Благодарю

**Comment by Tseka85** [comment]
Файл   admin/controller/extension/module/exchange1c.php
<https://github.com/Levitskyi-M/opencart2-exchange1c/commit/21437617b841b7e14a498f18888bf0ff08686e43#diff-7cdb1560cdbe04aa1bd02cbb400f6b69>
 в нём находим на 108 строке

if ($this->config->get('exchange1c_'.$param)) {

Меняем на :

              if ($this->config->get('exchange1c_'.$param) !== null) {

ср, 7 окт. 2020 г. в 15:31, pavelhar <notifications@github.com>:

**Comment by pavelhar** [comment]
Спасибо, всё работает))
Еще вопрос, в настройках характеристик (опций) есть настройка desc_option_image_import, это картинка опции верно?
Это реализовано или еще в стадии разработки?

**Comment by Tseka85** [comment]
Не реализовано.

**Comment by pavelhar** [comment]
Могу Вам скинуть доработку со стороны 1с, для картинок характеристик, реализовывали под модуль _neoseo_, к сожалению, с их модуля не смогу ничего отправить для доработки на стороне Вашего модуля, их модуль закодирован
