### ISSUE TITLE
Вывод артикула и ШК в характеристиках товара.

### ISSUE THREAD

**Issue by vavo2009** [Tseka85/opencart3-exchange1c#23]
Можно ли реализовать в модуле, чтобы артикул товара и штрихкод из 1С так же добавлялся в характеристики товара, соответственно в настройке модуля это включалось и выкл ( для тех кому необходимо).
Они изначально из 1С переносятся в базу, но нужно отнести их к характеристикам товара. В 1С характеристики реализуются созданием доп реквизитов для каждого вида номенклатуры. Но делать для них доп. реквизит(дублировать) Артикул и ШК в 1С это лишь забивать базу.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
