### ISSUE TITLE
Розница 2.2

### ISSUE THREAD

**Issue by dinjoker** [Tseka85/opencart3-exchange1c#24]
Модуль отлично справляется с выгрузкой товаров, категорий, атрибутов. Большое спасибо за ваш труд. Но к сожалению не обменивается заказами. Возможно адаптировать под 1С Розница 2.2?
Пробовал ставить в модуле УТ11. При обмене в 1С сообщает об успешном исполнении, но заказы не формируются. На стороне сайта файлы xml создает.

**Comment by Tseka85** [comment]
Приветствую , с Розницей надо отдельно разобраться . Будет время глянем ...

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
