### ISSUE TITLE
Кодировка orders.xml (order.xml)

### ISSUE THREAD

**Issue by Anonames** [Tseka85/opencart3-exchange1c#25]
Столкнулся с проблемой импорта заказов в 1с 8.3 УТП. Возможно дело в моей конфигурации 1С.
1. Отказывается импортировать orders.xml требует order.xml 
Тут все просто переименовываем по коду orders.xml в order.xml и все.

2. Файлы orders.xml или order.xml  формируются без BOM и не грузится в 1с 8.3 УТП.
Если фаил order.xml я открываю блокнотом (notepad) и сохраняю без изменений то BOM появляется (проверено notepad++) и фаил грузится без ошибок. Но при автоматическом обмене не прокатит, открывать и пересохранять
фаил.
Нашел в инете:
The UTF-8 BOM seems to be 0xEF 0xBB 0xBF, so you can attach it to your string after conversion to UTF-8.
$utf8_with_bom = chr(239) . chr(187) . chr(191) . $utf8_string;

Как я понял нужно добавить chr(239) chr(187) chr(191) в начало order.xml и BOM появится.
Но ни как не могу прикрутить это к формированию order.xml
Может подскажете как или есть другой путь.

ocStore 3.0.2.0
Версия 1с 8.3 УТП.

**Comment by Anonames** [comment]
Попробовал автоматический обмен:
Ошибка в 1С

Обмен заказами завершен с ошибками!!!
Произошла ошибка: . По причине: 

Не удалось разобрать данные, загруженные с сервера.
Обмен не выполнен

**Comment by Anonames** [comment]
Продолжаю эксперименты, возможно будет кому то полезно.
Включил опцию в заказах Конвертировать заказы в Windows-1251:
и Ошибка в 1С пропала, автоматический обмен заработал.
НО: Теперь не работает "Скачать заказы" в "Ручной обработке" хотя в  cash этот файл обновляется...

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
