### ISSUE TITLE
Разбивка наименования на порядок сортировки и наименование категории

### ISSUE THREAD

**Issue by staniki** [Tseka85/opencart3-exchange1c#26]
"Разбивка наименования на порядок сортировки и наименование категории по примеру "1. Телефоны" будет разбито на сортировка = 1, наименование = "Телефоны" Порядок сортировки необязателен, с начала строки до точки с пробелом будет переведено в число. Если будет задано дополнительное свойство категории "Сортировка", то оно будет иметь приоритет, то есть название будет разделено, но сортировка не будет взята из названия."

Я так понимаю данная функция отключена или вырезана?
Вот что написал @Kirillove в теме про 2.3:
"Временно убрал, это, добавлю позже включение в настройки."

Можно ли активировать/добавить эту функцию?

**Comment by Tseka85** [comment]
Она была до версии 1.6.4.1 ?

**Comment by staniki** [comment]
К сожалению не знаю, пост был написал автором в 2018 году. Я так понимаю до какой-то определенной версии этот функционал был. Потом автор его выпилил (закомментил?) и так и не добавил обратно.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
