### ISSUE TITLE
Пропадают Акции и Скидки в существующих товарах

### ISSUE THREAD

**Issue by StivSigal** [Tseka85/opencart3-exchange1c#29]
При установленной опции **Не загружать цены: Да**
Цены прописанные как  Акции и Скидки для групп покупателей "Связь типов цен (соглашений) в 1С с группами покупателей" **Удаляются**  
При **"Нет"**  Акций и Скидки которых нет в 1С то же удаляются.
то есть:
Часть Акций и Скидок заполняется в ручную а часть грузится из 1С
При обмене с 1С остаются только те Акции Скидки которые грузились из 1С
Посоветуйте как отключить изменение\удаление Цен, Акций и Скидок?
Спасибо.
OC3, 1с 8.3

**Comment by Tseka85** [comment]
Только изменениями в коде .

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
