### ISSUE TITLE
Ошибка при соединении с 1с

### ISSUE THREAD

**Issue by enhill** [Tseka85/opencart3-exchange1c#3]
`Fatal error: Uncaught Error: Class 'Openbay' not found in /home/site.ru/www/export/exchange1c.php:190 Stack trace: #0 {main} thrown in /home/site.ru/www/export/exchange1c.php on line 190`

В файле exchange1c.php идет регистрация класа openbay. 

`//OpenBay Pro`
`$registry->set('openbay', new Openbay($registry));`

В Opencart 3.0.3.6 "Русская сборка" Openbay возможно убран (я его найти не смог).

При удалении строк регистрации opanbay из файла exchange1c.php пропадает ошибка и обмен работает отлично. Участвует ли этот класс в обмене или его можно безболезненно выпилить?

**Comment by Tseka85** [comment]
В Opencart 3.0.3.6 удален openbay pro - заменён на OpenCart Marketplace

Можете выпилить .
