### ISSUE TITLE
Характеристики товаров в 1С и OpenCart

### ISSUE THREAD

**Issue by Anonames** [Tseka85/opencart3-exchange1c#30]
Добрый день, подскажите пожалуйста: 
Выгрузка заказа в 1С - не заполняются характеристики в заказах сайта.
Вроде характеристики модуль поддерживает или это касается только импорта товара?
Кто сталкивался с подобной проблемой в 1С 8.3 может можно автоматически заполнять
характеристики товара в заказе?
OC3, 1с 8.3

**Comment by Tseka85** [comment]
Добрый день ,  это касается только импорта товара.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
