### ISSUE TITLE
Не срабатывает опция "Не показывать товар с нулевым остатком"

### ISSUE THREAD

**Issue by ellamozg** [Tseka85/opencart3-exchange1c#31]
В опции "Не показывать товар с нулевым остатком" выставляю "Да", но товары с нулевым остатком все равно видны на сайте. В карточке таких товаров указывается, что товара нет в наличии, но мне необходимо, чтобы клиент вообще никак не видел товары с нулевым остатком. Возможно ли решить эту проблему?

**Comment by Tseka85** [comment]
Добрый день , чуть позже внесу правки .

**Comment by ellamozg** [comment]
Спасибо. Буду очень ждать.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
