### ISSUE TITLE
Ошибка при автоматической выгрузке  товаров на сайт

### ISSUE THREAD

**Issue by streqa** [Tseka85/opencart3-exchange1c#34]
Всем привет, проблема возникает при автоматической выгрузке товаров на сайт (ocStore 3.0.2.0), пишет:
"Ошибка экспорт файла "import.xml" на сайт. successfully import catalog"
Просьба поделиться мыслями или решением кто сталкивался, спасибо!

**Comment by streqa** [comment]
Если у кого-то было подобное - обновите программу до последней версии

**Comment by Tseka85** [comment]
А до этого какая у вас стояла версия ?

**Comment by streqa** [comment]
Как то не посмотрел, но она прям старая-старая была, накатил 2 обновления на нее 4.6.123 и следом 4.6.211

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
