### ISSUE TITLE
А есть формат файла обмена? Что бы самописную конфигурацию 1С приспособить. Или может обработка выгрузки отдельно есть?

### ISSUE THREAD

**Issue by evgeniiruchko** [Tseka85/opencart3-exchange1c#36]

**Comment by Tseka85** [comment]
Формат обмена стандартный commerceML 2

https://v8.1c.ru/tekhnologii/obmen-dannymi-i-integratsiya/standarty-i-formaty/standarty-commerceml/commerceml-2/

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
