### ISSUE TITLE
функция приведения к нижнему регистру

### ISSUE THREAD

**Issue by artem314** [Tseka85/opencart3-exchange1c#37]
strtolower($name) ->mb_strtolower($name, 'UTF-8')

https://github.com/Tseka85/opencart3-exchange1c/blob/fc6ea740029bc40d256bd1c6e09f724f6bc471f0/upload/admin/model/extension/exchange1c.php#L2682

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
