### ISSUE TITLE
Не загружает файлы import и offers

### ISSUE THREAD

**Issue by oleg990** [Tseka85/opencart3-exchange1c#4]
Подскажите пожалуйста.
1с(розница) пишет-обмен выполнен.файлы import и offers на ftp приходят,но автоматически не загружаются на сайт(ocstore 3.0).
Файлы в вроде в норме-при ручной загрузке товары появляются

А если всю эту процедуру делать из 1С УТ 10.3 , тогда обмен проходит - все четко, только характеристики обуви(размеры) не выгружаются на сайт.

**Comment by Tseka85** [comment]
Нужны логи загрузки на сайт .

**Comment by oleg990** [comment]
[error.log](https://github.com/Tseka85/opencart3-exchange1c/files/5363781/error.log)
[exchange1c.log](https://github.com/Tseka85/opencart3-exchange1c/files/5363782/exchange1c.log)

**Comment by Tseka85** [comment]
Логи очистите и попробуйте ещё раз сделать обмен . 
Желательно ещё логи самого сервера .
И если загружаете обмен в .zip , лучше ставить "**Максимальный размер файла: 81M**"

**Comment by oleg990** [comment]
Логи после обмена с 1с Розница 

Лог error -пустой

[exchange1c.log](https://github.com/Tseka85/opencart3-exchange1c/files/5364345/exchange1c.log)

**Comment by oleg990** [comment]
Логи после обмена с 1с  УТ
error - пустой
[exchange1c.log](https://github.com/Tseka85/opencart3-exchange1c/files/5364372/exchange1c.log)

**Comment by oleg990** [comment]
А логи сервера, это какие?(извините если поттупливаю)

**Comment by Tseka85** [comment]
Я ничего не нахожу .  Попробуйте перезалить файлы с гитхаба к себе на сервер . Я недавно вносил правки .

**Comment by oleg990** [comment]
файлы перезалил,не помогло,может где то что то подправить надо что бы модуль команду дал на загрузку пришедших файлов?

**Comment by Tseka85** [comment]
Кидайте скрины настроек ...

**Comment by oleg990** [comment]
настройки и фалы import и offers
[webdata.zip](https://github.com/Tseka85/opencart3-exchange1c/files/5401070/webdata.zip)

[Documents.zip](https://github.com/Tseka85/opencart3-exchange1c/files/5400929/Documents.zip)

**Comment by Tseka85** [comment]
Настройки в норме , кроме не установленного  логина  и пароля, надеюсь он у вас  установлен.

У вас товары есть в Опенкарте или магазин пустой ?

**Comment by oleg990** [comment]
Пустой

**Comment by oleg990** [comment]
Я уже думал может по Cron как то настроить что бы 1С по расписанию файлы выгружала а Cron'ом загружать по заданию как нибудь(толко я в этом не силен)

**Comment by Tseka85** [comment]
После обмена , у вас товар не появляется в опенкарте в каталоге ?

**Comment by oleg990** [comment]
нет

**Comment by Tseka85** [comment]
У вас есть доступ в БД ? Надо глянуть таблицу  product_to_1c

**Comment by oleg990** [comment]
да ,есть

**Comment by Tseka85** [comment]
Гляньте эту таблицу , она пустая после выгрузки ?

**Comment by Tseka85** [comment]
Давайте начнём с начала . 

1) Почистите все логи . 
2) Установите так

![отладка exchange1C](https://user-images.githubusercontent.com/31914380/96439776-a8c19380-120f-11eb-8050-728a96085dbc.jpg)

3) Сделайте обмен и вышлите мне лог.

**Comment by Tseka85** [comment]
Настройки пока не трогайте . 
И какая у вас  учетная система 1С ?

**Comment by oleg990** [comment]
1с
![1c](https://user-images.githubusercontent.com/72703111/96440451-a7dd3180-1210-11eb-876c-dc89d2e36f97.jpg)

**Comment by oleg990** [comment]
![1c](https://user-images.githubusercontent.com/72703111/96440557-d22eef00-1210-11eb-86da-47e3e3d534bc.jpg)

**Comment by oleg990** [comment]
лог после обмена
[exchange1c.log](https://github.com/Tseka85/opencart3-exchange1c/files/5401174/exchange1c.log)

**Comment by oleg990** [comment]
![Uploading product to 1c.jpg…]()

**Comment by oleg990** [comment]
![product to 1c](https://user-images.githubusercontent.com/72703111/96441072-8fb9e200-1211-11eb-981b-6fb92dff2957.jpg)

**Comment by Tseka85** [comment]
Попробую разобраться . Позже напишу ответ . Есть пару вариантов .

**Comment by oleg990** [comment]
ок,спасибо

**Comment by oleg990** [comment]
поставил настройку : Загружать остатки по складам:  Нет
и лог поменялся
[exchange1c.log](https://github.com/Tseka85/opencart3-exchange1c/files/5402117/exchange1c.log)

**Comment by Tseka85** [comment]
А в другом логе есть сообщения ?

**Comment by oleg990** [comment]
нет

**Comment by Tseka85** [comment]
Возможно идёт ошибка во время парсинга xml файла .

**Comment by Tseka85** [comment]
Вы в ручную файл offers загружали ?

**Comment by oleg990** [comment]
мне бы наладить этот процесс-могу отблагодарить)

**Comment by oleg990** [comment]
забыл сказать, по Cron'у ("http://SITE.RU/export/exchange1c.php?module=cronImport");,      импорт и офферс загружаются

**Comment by Tseka85** [comment]
Да , я видел по логам . Тут проблема со стороны 1С Розница . Пытаюсь разобраться ...

**Comment by oleg990** [comment]
спасибо,очень жду

**Comment by Tseka85** [comment]
Розница 2.3  не передаёт последний запрос на сайт .  

Первый запрос, mode=checkauth  -- авторизация 

Второй запрос, mode=init   --   запрос настроек для передачи

Третий запрос, mode=file + POST zip-файла.   -- запрос на передачу файла для временного хранения 

Последующие запросы, mode=import  -- Импорт данных из файла xml

**Comment by oleg990** [comment]
ну тогда есть какой нибудь вариант по CRON как то автоматически файлы загружать?

**Comment by Tseka85** [comment]
Есть. В настройках есть инструкция .
