### ISSUE TITLE
Настройка обмена с 1С

### ISSUE THREAD

**Issue by Jazzzz1** [Tseka85/opencart3-exchange1c#43]
При попытке перехода на http://postroikamarket.ru/export/exchange1c.php выдает:

Подобную проблему видел у кого-то, помогала полная переустановка модуля и сайта на другом хостинге. Но хочется понять проблему и победить малой кровью. Чего оно хочет? ОС v 3.0.3.2

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Session::__construct(), 0 passed in /var/www/u0555865/data/www/postroikamarket.ru/export/exchange1c.php on line 138 and at least 1 expected in /var/www/u0555865/data/www/postroikamarket.ru/system/library/session.php:24 Stack trace: #0 /var/www/u0555865/data/www/postroikamarket.ru/export/exchange1c.php(138): Session->__construct() #1 {main} thrown in /var/www/u0555865/data/www/postroikamarket.ru/system/library/session.php on line 24

**Comment by Tseka85** [comment]
Вы точно залили все файлы с этого https://github.com/Tseka85/opencart3-exchange1c/tree/master/upload   ?

**Comment by Jazzzz1** [comment]
Да, вы были правы. Видимо что-то забыл. Спасибо. Обмен пока нет возможности проверить, но заветный success я на нужной странице увидел. Благодарю.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
