### ISSUE TITLE
Обмен 1с ошибки

### ISSUE THREAD

**Issue by rus9595** [Tseka85/opencart3-exchange1c#44]
Добрый день. Возникла такая проблема, если товаров выгружаю 200, то все ок идет обмен, а если на выгрузку ставлю товаров 600, то происходит постоянно крашь
в 1с пишет вот что
Выгружено товаров: 643
Выгружено картинок: 619
Выгружено файлов: 0
Выгружено предложений: 575
Получен расширенный статус успешного завершения сеанса
Ответ сервера:
Successfully import catalog 

Произошла ошибка на стороне сервера. Получен неизвестный статус импорта.
Обмен не выполнен
Ответ сервера:
Successfully processed file: /storage/cache/exchange1c/import.xml

Выгрузка товаров завершена с ошибками!!!

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
