### ISSUE TITLE
Ошибка обмена + не выводятся характеристики и следом цены

### ISSUE THREAD

**Issue by Devastator648** [Tseka85/opencart3-exchange1c#46]
Здравствуйте! Не выводятся характеристики, к которым подтянуты цены! Так же 1с пишет ошибку:
`Интерактивный обмен
15.11.2022 17:17:02 Запуск выгрузки товаров
15.11.2022 17:17:17 Выгрузка на сайт завершилась с ошибками.
import.xml: Произошла ошибка на стороне сервера.
Ответ сервера: 
failure
ERROR: 2004
15.11.2022 17:17:24 offers.xml Пакет успешно выгружен на сайт.
15.11.2022 17:17:24 Завершено формирование файлов выгрузки товаров
Выгружено товаров: 53
предложений: 78
картинок: 37
файлов: 0

В том числе для каталога Основной каталог товаров:
товаров: 53
предложений: 78
картинок: 37
файлов: 0

Ошибки в процессе выгрузки каталога Основной каталог товаров:15.11.2022 17:17:02 Запуск выгрузки товаров
15.11.2022 17:17:17 Выгрузка на сайт завершилась с ошибками.
import.xml: Произошла ошибка на стороне сервера.
Ответ сервера: 
failure
ERROR: 2004

15.11.2022 17:17:24 Завершена выгрузка товаров`

**Comment by ATropichev** [comment]
Нужно файлы выгрузки посмотреть.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
