### ISSUE TITLE
Не работает seo url

### ISSUE THREAD

**Issue by WEBBRACE** [Tseka85/opencart3-exchange1c#5]
Привет! Благодарен за модуль, но есть проблема с seo url, по какой то причине при генерации url не проставляется язык сайта, из за этого ссылки не работают.
![7e1eb38cc4](https://user-images.githubusercontent.com/34915921/95731928-c67b7f80-0c88-11eb-8a61-b0aa7d7400bc.jpg)

**Comment by Tseka85** [comment]
У вас один язык ?

**Comment by WEBBRACE** [comment]
> У вас один язык ?

Да

**Comment by Tseka85** [comment]
> генерации url не проставляется язык

 Выборочно не проставляется или всем ?

**Comment by Tseka85** [comment]
Надо логи смотреть . Так тяжело понять .

**Comment by WEBBRACE** [comment]
> > генерации url не проставляется язык
> 
> Выборочно не проставляется или всем ?

На все товары, которые загружаются на сайт

**Comment by WEBBRACE** [comment]
Во вложении лог файл.
[exchange1c.log](https://github.com/Tseka85/opencart3-exchange1c/files/5365090/exchange1c.log)

**Comment by Tseka85** [comment]
Вроде нашёл ошибку . В OC 2.3  не надо было заполнять поле языка, его там попросту нет  , а вот в OC 3 оно уже появилось.

**Comment by Tseka85** [comment]
![oc_seo_url](https://user-images.githubusercontent.com/31914380/95763268-7c5dc280-0cb7-11eb-8836-cb7dea9f1864.jpg)
![oc_url_alias](https://user-images.githubusercontent.com/31914380/95763272-7d8eef80-0cb7-11eb-87fe-4c467a81afa9.jpg)

**Comment by Tseka85** [comment]
Скоро внесу исправления .

**Comment by WEBBRACE** [comment]
> Скоро внесу исправления .

Буду очень признателен! Отпишите пожалуйста когда закончите.

**Comment by Tseka85** [comment]
Поправил.
