### ISSUE TITLE
Как можно сделать так что бы товары с сайта попадали в 1с?

### ISSUE THREAD

**Issue by Vladislavlr** [Tseka85/opencart3-exchange1c#50]

**Comment by Tseka85** [comment]
Пока нет такой возможности.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
