### ISSUE TITLE
Свойства не удаляются

### ISSUE THREAD

**Issue by korvinod** [Tseka85/opencart3-exchange1c#53]
Если свойства товара созданы выгрузкой из 1С - товар перестает быть редактируемым.. 
`
[Sat Feb 04 16:41:16.168483 2023] [proxy_fcgi:error] [pid 129535:tid 140515483838208] [client 78.26.147.179:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Error: Cannot delete or update a parent row: a foreign key constraint fails (`database`.`oc_product_feature_value`, CONSTRAINT `oc_product_feature_value_ibfk_2` FOREIGN KEY (`product_option_id`) REFERENCES `oc_product_option` (`product_option_id`))<br />Error No: 1451<br />DELETE FROM oc_product_option WHERE product_id = '7' in /full_path/public_html/system/library/db/mysqli.php:41\nStack trace:\n#0 /full_path/public_html/system/library/db.php(45): DB\\MySQLi->query('DELETE FROM oc_...')\n#1 /full_path/public_html/admin/model/catalog/product.php(199): DB->query('DELETE FROM oc_...')\n#2 /full_path/public_html/storage/modification/system/engine/loader.php(248): ModelCatalogProduct->editProduct('7', Array)\n#3 /full_path/public_html/system/engine/proxy.php(47): Loader->{closure}(Array, Array)\n#4 /full_path/public_html/storage/modification/admin/cont...', referer: https://mysite.com/admin/index.php?route=catalog/product/edit&user_token=DJWNinCiHwDd06fHJ478oF8Oe7LJ19rt&product_id=7&page=2

`

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
