### ISSUE TITLE
Как выбрать Украина 2.3

### ISSUE THREAD

**Issue by Feldeshi** [Tseka85/opencart3-exchange1c#56]
После установки модуля, в подключении нету Управление торговлей для Украины 2.3 (!)
через другие варианты не получается связаться с 1с

**Comment by ATropichev** [comment]
Вы устанавливали в 1С [модуль от Битрикс?](https://1c.bitrix.ua/ecommerce/download.php)
Какие сообщения об ошибке отображаются в 1С при попытке соединения?

**Comment by Feldeshi** [comment]
> Вы устанавливали в 1С [модуль от Битрикс?](https://1c.bitrix.ua/ecommerce/download.php) Какие сообщения об ошибке отображаются в 1С при попытке соединения?

1С пишет "Не удалось установить соединение с сервером. Авторизация пользователя не выполнена."
Сейчас попробую обновить модули по Вашей ссылке

И вопрос, в настройках модуля какой режим выбирать? если стоит 1С 8.3

**Comment by ATropichev** [comment]
Про проблему с авторизацией можно почитать [здесь](https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/)
Выбор программы в настройках влияет на загрузку реквизитов организации, количества и базовой единицы измерения (если я правильно помню).  Это на подключении не сказывается, так что можно попробовать чисто экспериментально.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
