### ISSUE TITLE
Как выбрать каталог загрузки

### ISSUE THREAD

**Issue by AlexusTdV** [Tseka85/opencart3-exchange1c#57]
В старой версии в настройках модуля был выбор каталога. В изменённой под 3.0 нет такой функции. Как быть?

**Comment by ATropichev** [comment]
Выбор каталога это как? Выбор категории верхнего уровня?

**Comment by AlexusTdV** [comment]
> Выбор каталога это как? Выбор категории верхнего уровня?

Нет. В старом модуле был раздел "Связь каталога ТС с магазином". Там прописывался ID каталога, из которого происходит загрузка товаров.
В новой версии такого раздела нет. 
В общем как выбрать товары, которые загружать из 1С?

**Comment by ATropichev** [comment]
Мне это почему-то Битрикс напоминает. Если не сложно приложите скриншот старой версии, чтобы было понятно.
>В общем как выбрать товары, которые загружать из 1С?
Это на стороне 1С выбирается, там в выгрузке есть отбор.

**Comment by AlexusTdV** [comment]
> Мне это почему-то Битрикс напоминает. Если не сложно приложите скриншот старой версии, чтобы было понятно.
> 
> > В общем как выбрать товары, которые загружать из 1С?
> > Это на стороне 1С выбирается, там в выгрузке есть отбор.

[https://ibb.co/gd09tks](https://ibb.co/gd09tks)

**Comment by ATropichev** [comment]
У вас несколько магазинов на сайте?

**Comment by AlexusTdV** [comment]
> У вас несколько магазинов на сайте?

Нет, один. На скрине ID списка, в который заносятся товары для выгрузки. Такой настройки почему то в данном модуле нет.

**Comment by ATropichev** [comment]
Если один магазин, то это не нужно. Делаете отбор товаров при выгрузке на стороне 1С. То что 1С выгрузит попадёт в каталог (он у магазина один, не как в Битрикс) 
На скрине, скорее всего, какой-то другой модуль. Вот [модуль для OC 2](https://github.com/KirilLoveVE/exchange1c_v1.6_oc2.3) на основе которого сделан этот. Там такого функционала нет. По крайней мере в исходниках я не вижу.

**Comment by AlexusTdV** [comment]
> Если один магазин, то это не нужно. Делаете отбор товаров при выгрузке на стороне 1С. То что 1С выгрузит попадёт в каталог (он у магазина один, не как в Битрикс) На скрине, скорее всего, какой-то другой модуль. Вот [модуль для OC 2](https://github.com/KirilLoveVE/exchange1c_v1.6_oc2.3) на основе которого сделан этот. Там такого функционала нет. По крайней мере в исходниках я не вижу.

Так а как выделать товары для выгрузки тогда?

**Comment by ATropichev** [comment]
В какой конфигурации 1С вы работаете?

**Comment by AlexusTdV** [comment]
> В какой конфигурации 1С вы работаете?

В смысле какой? Я в 1С не особо разбираюсь

**Comment by ATropichev** [comment]
У вас выгрузка на сайт на [вот это](https://aspro.ru/upload/tires2/Instruktsiya_po_integratsii_s_1S/image22.png) похожа?

**Comment by AlexusTdV** [comment]
> У вас выгрузка на сайт на [вот это](https://aspro.ru/upload/tires2/Instruktsiya_po_integratsii_s_1S/image22.png) похожа?

Именно так. Этот ID каталога нужно в настройках где то указать, а где я не вижу.

**Comment by ATropichev** [comment]
Если как на картинке, нажмите "Настроить отбор" над списком каталогов. Там можно настроить отбор. И группы номенклатуры посмотрите. Идентификатор здесь, я думаю, не важен.

**Comment by AlexusTdV** [comment]
> Если как на картинке, нажмите "Настроить отбор" над списком каталогов. Там можно настроить отбор. И группы номенклатуры посмотрите. Идентификатор здесь, я думаю, не важен.

У нас есть старый сайт, с которым обмен работает. Пытаюсь выгрузку сделать на новый сайт. Скопировал узел обмена, поменял данные на новые (связь с сайтом работает). Указал в каталоге товар. Обмен происходит, выбранный товар не выгружается...

**Comment by ATropichev** [comment]
Лог включить и посмотреть что конкретно происходит.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/?page=205  лучше тут задать вопрос. Пока этим модулем не занимаюсь.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
