### ISSUE TITLE
Помогите срочно

### ISSUE THREAD

**Issue by imamverdiyev** [Tseka85/opencart3-exchange1c#58]
Нужно немножечко переделать модуль (платно конечно) , свяжитесь пожалуйста со мной для обсуждения деталей +994773331712 (whatsapp)

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/?page=205  тут вам точно помогут.

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
