### ISSUE TITLE
При Обмене 1С и сайта проблема

### ISSUE THREAD

**Issue by oleg990** [Tseka85/opencart3-exchange1c#6]
Не удалось установить соединение с сервером. Проверьте имя пользователя и пароль.
Fatal 1009
Хотя 2 дня назад вся работало,помогите пжл.
[логи.zip](https://github.com/Tseka85/opencart3-exchange1c/files/5372710/default.zip)

**Comment by Tseka85** [comment]
PHP Fatal error:  require_once(): Failed opening required '../admin/config.php'   

У вас файл конфигурации по этому пути /admin/config.php  ?

**Comment by oleg990** [comment]
Да

**Comment by Tseka85** [comment]
Код ошибки 1009 
Неизвестный метод авторизации, проверьте переменную $_SERVER, содержимое этой переменной выведен в лог ниже.

**Comment by oleg990** [comment]
Проверял,все как в исходном файле

**Comment by Tseka85** [comment]
Судя по логам , у вас проблема на стороне сервера. Что-то с путями не так .

**Comment by Tseka85** [comment]
Проверьте наличие записи в файле .htaccess в корне файла после 
RewriteEngine On

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

**Comment by oleg990** [comment]
в .htaccess записи есть!

ругается на 
respect-obuv.ru/export/exchange1c.php?type=catalog&mode=checkauth
Проверьте наличие записи в файле .htaccess в корне файла после RewriteEngine On:
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

---------------------------------ВОТ КАК У МЕНЯ СЕЙЧАС-----------------------

# 1.To use URL Alias you need to be running apache with mod_rewrite enabled.

# 2. In your opencart directory rename htaccess.txt to .htaccess.

# For any support issues please visit: http://www.opencart.com

Options +FollowSymlinks

# Prevent Directoy listing
Options -Indexes

# Prevent Direct Access to files
<FilesMatch "(?i)((\.tpl|.twig|\.ini|\.log|(?<!robots)\.txt))">
 Require all denied
## For apache 2.2 and older, replace "Require all denied" with these two lines :
# Order deny,allow
# Deny from all
</FilesMatch>

# SEO URL Settings
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
# If your opencart installation does not run on the main web folder make sure you folder it does run in ie. / becomes /shop/

RewriteBase /
RewriteRule ^sitemap.xml$ index.php?route=extension/feed/google_sitemap [L]
RewriteRule ^googlebase.xml$ index.php?route=extension/feed/google_base [L]
RewriteRule ^system/storage/(.*) index.php?route=error/not_found [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]

### Additional Settings that may need to be enabled for some servers
### Uncomment the commands by removing the # sign in front of it.
### If you get an "Internal Server Error 500" after enabling any of the following settings, restore the # as this means your host doesn't allow that.

# 1. If your cart only allows you to add one item at a time, it is possible register_globals is on. This may work to disable it:
# php_flag register_globals off

# 2. If your cart has magic quotes enabled, This may work to disable it:
# php_flag magic_quotes_gpc Off

# 3. Set max upload file size. Most hosts will limit this and not allow it to be overridden but you can try
# php_value upload_max_filesize 999M

# 4. set max post size. uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value post_max_size 999M

# 5. set max time script can take. uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value max_execution_time 200

# 6. set max time for input to be recieved. Uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value max_input_time 200

# 7. disable open_basedir limitations
# php_admin_value open_basedir none
