### ISSUE TITLE
Мультиязычность - а подскажите как работает?

### ISSUE THREAD

**Issue by vsklyarenko85** [Tseka85/opencart3-exchange1c#60]
Доброго времени суток!
Подскажите а как грузить товары в мультиязычном магазине. Сейчас загрузка происходит по языку установленому по умолчанию. А как второй язык загрузить ума не приложу, или нет такой функции

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
