### ISSUE TITLE
не работает ручная обработка скачать заказы

### ISSUE THREAD

**Issue by vitaliititan777** [Tseka85/opencart3-exchange1c#61]
Добрый день! 
подскажите почему может не работать ручная обработка скачать заказы?
рабочий сайт с  на ocStore 3.0.3.7, файл не скачивается, нажимаю кнопку и белый экран по ссылке сайт.ком/admin/index.php?route=extension/module/exchange1c/downloadOrders&user_token=XEXEtG1JVngon6pn7ZF21YXSKKuuNOyL.
Потом поставил модуль на чистый ocStore 3.0.3.7, заказы скачиваются и выгружаются в xml.
это может быть конфликт с другими модулями, например Новая Почта API?

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.
