### ISSUE TITLE
Выгрузка заказов, обмен статусов без загрузки товаров 

### ISSUE THREAD

**Issue by vitaliititan777** [Tseka85/opencart3-exchange1c#62]
Подскажите возможен  только такой режим работы чтоб выгружать заказы в 1С и двусторонний обмен статусами заказов?
товары и код товар совпадает.
мне не нужно загружать на сайт этим модулем товары, категории, цены, остатки, только работа с заказами и статусами заказов.
в настройках модуля не вижу кнопки "не загружать товары"

**Comment by Tseka85** [comment]
https://opencartforum.com/topic/60560-modul-modul-obmena-dlya-opencart-v23-po-standartu-commerceml-podderzhka/ 
Пишите сюда все ваши вопросы по настройки.

**Comment by vitaliititan777** [comment]
к сожалению в этой теме на опенкартфорум нет порддержки уже несколько месяцев и участники там не активны.
возможно вы сможете помочь за дополнительную плату?
напишите свой телеграмм как с вами связаться
