### ISSUE TITLE
Дубли при синхронизации заказов.

### ISSUE THREAD

**Issue by Rad1s** [Tseka85/opencart3-exchange1c#8]
Добрый день! 
Спасибо за модуль, товары из Subtotal в Opencart выгружает. Такая проблема: При покупке товара на сайте opencart в Subtotal появляется дубль этого товара вместо того, чтобы оформить продажу имеющегося товара.
Из Subtotal нормально выгружаются поля Наименование, цена, количество на складе и артикул (в поле Модель). Но не выгружается поле Штрихкод. Может быть в этом дело? Или нужно как-то настроить поле, по которому будет найден товар в Subtotal, на который пришел заказ.

**Comment by Tseka85** [comment]
Добрый день . У вас настройки как на картинке ниже ?
![синхронизация по ГУИД](https://user-images.githubusercontent.com/31914380/97700470-93bcee00-1ab4-11eb-8629-ff816448cad8.jpg)

**Comment by Rad1s** [comment]
Да

**Comment by Rad1s** [comment]
> Добрый день . У вас настройки как на картинке ниже ?
> ![синхронизация по ГУИД](https://user-images.githubusercontent.com/31914380/97700470-93bcee00-1ab4-11eb-8629-ff816448cad8.jpg)

**Comment by Tseka85** [comment]
> Subtotal появляется дубль этого товара вместо того, чтобы оформить продажу имеющегося товара.

Не много не понятно , каким образом он создаёт новый товар в Subtotal . Этот модуль не может выгружать товар из Опенкарта в 1С или Subtotal . Только из 1С в опенкарт .  Двух сторонний обмен только заказами .

**Comment by Rad1s** [comment]
> > Subtotal появляется дубль этого товара вместо того, чтобы оформить продажу имеющегося товара.
> 
> Не много не понятно , каким образом он создаёт новый товар в Subtotal . Этот модуль не может выгружать товар из Опенкарта в 1С или Subtotal . Только из 1С в опенкарт . Двух сторонний обмен только заказами .

Во время синхронизации заказов и происходит создание дубля. [
![image](https://user-images.githubusercontent.com/73697576/97704018-73e8f280-1ad3-11eb-960a-cc5eab5a75cc.png)
](url)

**Comment by Tseka85** [comment]
Возможно это настройки вашего Subtotal . При выгрузки из Опенкарта передаётся xml файл с заказами и товарами которые в заказе . У каждого товара в xml файле свой УИД который должен быть такой же как и в Subtotal . 
 Я к сожалению не работал с Subtotal . Рекомендую вам обратится в службу поддержки Subtotal .

**Comment by Rad1s** [comment]
Понял. Поддержка тоже не смогла помочь, так как гарантирует работу модуля только на opencart 2. Спасибо.

**Comment by Tseka85** [comment]
> гарантирует работу модуля только на opencart 2

Поддержка Subtotal ? 

Причём тут разница версий ? Логика работы модуля абсолютно одинаковая для Opencart 2 и для Opencart 3.

**Comment by Rad1s** [comment]
Да, здесь они не отвечают за работоспособность модуля на opencart 3: https://subtotal.ru/support/apps/integratsiya-s-opencart

"Доступно для OpenCart версии 2.0.3.1. (работа с другими версиями возможна, но не гарантируется)."

Со ссылкой на эти строки, меня отправили искать решение самостоятельно, либо обращаться к разработчику модуля. 

Не подскажете, где смотреть XML файл заказа?

**Comment by Tseka85** [comment]
> Да, здесь они не отвечают за работоспособность модуля на opencart 3: https://subtotal.ru/support/apps/integratsiya-s-opencart

 На этой странице есть подробные настройки , вы всё правильно настроили ?

**Comment by Rad1s** [comment]
Да, конечно, настроил всё согласно инструкции.
