### ISSUE TITLE
Не передается цена .. 

### ISSUE THREAD

**Issue by AlexanderKopyl** [Tseka85/opencart3-exchange1c#9]
Все типы цен с 1С импортнулись .. Но цены почему-то не импортируются ..
Куда копать и в какую функцию ?
Благодарю

**Comment by Tseka85** [comment]
Сразу напишу , что проблема в ваших настойках модуля или 1С . Какая 1С у вас ?

**Comment by Anonames** [comment]
Добрый день та же беда, цена скидки и акции нормально загружается, а вот основная цена товара нет.
Версия 1с 8.3 УТП.
в логах ошибок нет
5432M Цена предложения: 0.0000
[price] => 0.0000
а должна быть как в акциях
![1C](https://user-images.githubusercontent.com/76214956/102625890-c7c89d00-414e-11eb-98ee-31ec3651ac8e.jpg)

**Comment by Tseka85** [comment]
Разберёмся . Можете пока обновить модель . Там было исправления связанное с дробным преобразованием .

**Comment by Anonames** [comment]
Спасибо.
обновил, переустановил модуль.
Основная Цена Товара не тянется. 
Если нужны какие нибудь логи могу предоставить.

**Comment by Tseka85** [comment]
Скиньте пожалуйста логи.

**Comment by AlektroNik** [comment]
> Opencart 3
> Версия 1с 8.3 УТП.

На связке 1С **УНФ 1.6** + Git **20201127** ocStore-ocstore-3-0-2-0 + opencart3-exchange1c-master.zip (**20201209**)
Протестировал, но проблем не наблюдаю.

А в offers.xml то все нормально, цена есть?

Вот мой пример. Может у Вас там запятая вместо точки или еще чего.
[Скрин](https://monosnap.com/file/Xbtbb75IcuvmxYpumBxtf6kC1fC41j)

Попробуйте вручную отредактировать offers.xml и выгрузить его на сайт.
Вот мои рабочии примеры из демо базы:
https://yadi.sk/d/qYDWAt_gCO6OYQ
https://yadi.sk/d/gIyOkYHXcB96Qw

**Comment by Anonames** [comment]
AlektroNik загрузил Ваши данные результат тот же - нет основной цены товара.
Понимаю что проблема где то у меня.
Снес все модификаторы, не помогло. Осталось только на чистой ocStore 3.0.2.0 проверить для успокоения.
Спасибо что помогаете и делитесь информацией.
[log.txt](https://github.com/Tseka85/opencart3-exchange1c/files/5728405/log.txt)

**Comment by AlektroNik** [comment]
А у меня в логе "exchange1c.log" нет поля [price] => 0.0000.

Судя по Вашим логам, мне кажется проблема на стороне сайта.
Попробуйте выставить параметры вот так:
**Не загружать цены: Нет
Пропускать нулевые цены: Нет**

Ну и да, как вариант, качнуть с github чисты ocStore и проверить воспроизводится проблема или нет.
Но я думаю скорее всего дело в какой-то настройке модуля обмена.
Или с параметром "Тип учетной системы" в модуле обмена ... заодно и его проверьте, что бы УТ 10.3 стоял, попробуйте перетыкнуть туда сюда.

Ну и как вариант ждать тогда пока @Tseka85 ответит. :)


2020-12-21 20:08:37 - 5122M Найдена цена 123000.21 (Розничная)
2020-12-21 20:08:37 - 5174M Цена товара 123000.21
2020-12-21 20:08:37 - 5122M Найдена цена 203.21 (Оптовая)
2020-12-21 20:08:37 - 5203M Цена акции 'Оптовая' = 203.21
2020-12-21 20:08:37 - 5122M Найдена цена 100.21 (Учетная)
2020-12-21 20:08:37 - 5203M Цена акции 'Учетная' = 100.21
2020-12-21 20:08:37 - 5122M Найдена цена 50 (Акции)
2020-12-21 20:08:37 - 5203M Цена акции 'Акции' = 50
2020-12-21 20:08:37 - 0106M Время обработки parse_price: 0.001680850982666 сек
2020-12-21 20:08:37 - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-12-21 20:08:37 - 2574M 
2020-12-21 20:08:37 - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-12-21 20:08:37 - 5611M ПРЕДЛОЖЕНИЕ
2020-12-21 20:08:37 - 5240M:
2020-12-21 20:08:37 - Array
(
    [product_id] => 462
    [guid] => 19360973-b5bb-11e4-8355-74d02b7dfd8c
    [version] => 
    [delete] => 0
)

**Comment by Tseka85** [comment]
Я отвечу ))) Очень много вопросов у меня задают по этому модулю . Я потихоньку разгребаю .

**Comment by AlektroNik** [comment]
@Tseka85 
Я понимаю. Хотел немного Ввс разгрузить.
Большое спасибо, что не бросаете проект.
Вам бы где-нибудь выложить ссылку "Поддержите проект" и благодарные люди бы кидали денюшку за решенные проблемы ... Чтобы стимул был )))

**Comment by Tseka85** [comment]
Спасибо . Сейчас заказов хватает на доработку .

**Comment by Anonames** [comment]
Модуль оказался не причем Вам спасибо за работу! 
Экспериментировал с настройками и таки да)) цены загрузил.
Немного поковырял фаил импорта offers.xml нашел что мои ID товаров имеют два кода разделенных #
<Ид>41a5e2d0-2952-11e0-b05d-001a4b4f0d7d#41a5e2d3-2952-11e0-b05d-001a4b4f0d7d</Ид>
а в import.xml только <Ид>41a5e2d0-2952-11e0-b05d-001a4b4f0d7d</Ид>
Буду душить 1с-ников.

**Comment by Anonames** [comment]
Из описания формата XML построенного на основе стандарта CommerceML 2.xx 
<Ид> - Идентификатор предложения. В отдельных случаях может иметь формат: <ид_товара>#<ид_элемента>
Это мой случай, ребята занимающиеся базой пожимают плечами, видимо не могут организовывать выгрузку по другому.
Возможно в будущем Вы сможете добавить поддержку такого формата в модуль.
Всем спасибо за участие и помощь.

**Comment by Tseka85** [comment]
Я думаю в скором времени добавлю такой формат .
